name: Build RasFocus Pro Max (Win32)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies via vcpkg
        shell: pwsh
        # গিটহাবের প্রি-ইনস্টল করা vcpkg এর অরিজিনাল পাথ ব্যবহার করা হলো
        run: |
          $vcpkg_path = "$env:VCPKG_INSTALLATION_ROOT\vcpkg.exe"
          & $vcpkg_path install opencv poppler qpdf libharu tesseract qrcodegen --triplet x64-windows
          & $vcpkg_path integrate install

      - name: Configure CMake
        shell: pwsh
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows -A x64

      - name: Build Executable
        run: |
          cd build
          cmake --build . --config Release

      - name: Upload EXE as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RasFocus-Pro-Max-App
          path: build/Release/RasFocusProMax.exe
